version: '2'
networks:
  default:
    ipam:
      driver: default
services:
  nginx:
    build:
      context: ./build/docker/nginx
      args:
        PROJECT_PUBLIC_PATH: ${PROJECT_PUBLIC_PATH}
        PROJECT_HOST: ${PROJECT_HOST}
        PROJECT_ROOT_PATH: ${PROJECT_ROOT_PATH}
    container_name: ${PROJECT_NAME}_nginx
    depends_on:
      - php
      - mysql
    volumes_from:
      - php
  php:
    build:
      context: ./build/docker/php
      args:
        PROJECT_ROOT_PATH: ${PROJECT_ROOT_PATH}
    container_name: ${PROJECT_NAME}_php
    volumes:
      - ./www:${PROJECT_ROOT_PATH}
  mysql:
    build: ./build/docker/mysql
    container_name: ${PROJECT_NAME}_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mysql_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password